feat: improve build stuff

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,21 +1,40 @@
 #!/bin/sh
 
+set -eu
+
 ROOT="${ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || echo ".")}"
 MODULE="$(go list -m)"
-DOMAIN="${DOMAIN:-localhost:5000}"
-SERVICE="${1:-${SERVICE:-$(command -v fzf >/dev/null 2>&1 && find "$ROOT/cmd" -maxdepth 1 -printf "%P\n" | fzf)}}" || exit 1
 DEVMODE="${DEVMODE:-0}"
 
 for arg in "$@"; do
 	case "$arg" in
-		-dev) DEVMODE=1 ;;
-		-*) echo "error: unkown option \"$arg\"" >&2; exit 1 ;;
-		*)
-			[ ! -d "$ROOT/cmd/$arg" ] && echo "error: service not found \"$arg\"">&2 && exit 1
-			SERVICE="$arg"
-			;;
+	-dev) DEVMODE=1 ;;
+	-*)
+		echo "$(basename "$0"): unkown option \"$arg\"" >&2
+		exit 1
+		;;
+	*)
+		[ ! -d "$ROOT/cmd/$arg" ] && echo "$(basename "$0"): service not found \"$arg\"" >&2 && exit 1
+		SERVICE="$arg"
+		;;
 	esac
 done
+
+[ -z "${SERVICE:-}" ] && {
+	services="$(find "$ROOT/cmd" -maxdepth 1 -printf "%P\n" | grep -v '^$')"
+	[ -z "$services" ] && {
+		echo "$(basename "$0"): no service found" >&2
+		exit 1
+	}
+	[ "$(echo "$services" | wc -l 2>/dev/null)" -eq 1 ] &&
+		SERVICE="$services" || {
+		command -v fzf >/dev/null 2>&1 &&
+			SERVICE="$(echo "$services" | fzf)"
+	} || {
+		echo "$(basename "$0"): no service selected" >&2
+		exit 1
+	}
+}
 
 src="$ROOT/cmd/$SERVICE"
 out="$ROOT/bin/$SERVICE"
@@ -24,7 +43,7 @@ BUILDTAG="$(date +v%Y%m%d)-$(git describe --tags --always --dirty)"
 [ "$DEVMODE" = 1 ] && BUILDTAG="$BUILDTAG-dev"
 GOVERSION="$(go version | cut -d " " -f 3- | tr " " "-")"
 SYSTEMTAG="$(uname -srm | tr " " "-" | tr "[:upper:]" "[:lower:]")"
-gotags="CGO_ENABLED=0 GOOS=linux GOARCH=amd64"
+gotags="CGO_ENABLED=0"
 
 echo "building $SERVICE on $SYSTEMTAG with $GOVERSION"
 echo "$gotags"
@@ -35,18 +54,18 @@ env $(echo "$gotags" | xargs) go build \
 	-ldflags "-s -w -extldflags=-static
 	-X=$MODULE/internal/buildinfo.BuildTag=$BUILDTAG
 	-X=$MODULE/internal/buildinfo.GoVersion=$GOVERSION
-	-X=$MODULE/internal/buildinfo.SystemTag=$SYSTEMTAG
-	-X=$MODULE/internal/serverinfo.Domain=$DOMAIN
-	-X=$MODULE/internal/serverinfo.Service=$SERVICE" \
+	-X=$MODULE/internal/buildinfo.SystemTag=$SYSTEMTAG" \
 	-o "$out" \
 	"$src"
 
 ec=$?
-[ $ec -eq 0 ] && echo "built successfully ($BUILDTAG)" || echo "build failed" >&2
+[ $ec -eq 0 ] &&
+	echo "built successfully ($BUILDTAG)" ||
+	echo "$(basename "$0"): build failed" >&2
 
 [ "$DEVMODE" != 1 ] && {
-	command -v strip >/dev/null 2>&1 && strip "$out"
-	command -v upx  >/dev/null 2>&1 && upx -q -9 "$out"
+	command -v strip >/dev/null 2>&1 && strip --strip-all "$out"
+	command -v upx >/dev/null 2>&1 && upx -q --best "$out"
 }
 
 exit $ec
